# Generated by Django 4.0.5 on 2022-07-03 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='Falta_imagen.jpg', null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contador', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(default='--', max_length=300)),
                ('nombre', models.CharField(default='--', max_length=300)),
                ('correo', models.CharField(default='--', max_length=300)),
                ('telefono', models.CharField(default='--', max_length=300)),
                ('region', models.CharField(default='--', max_length=300)),
                ('ciudad', models.CharField(default='--', max_length=300)),
                ('termino', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default='User_Defecto.jpg', upload_to='users')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_not', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='--', max_length=300)),
                ('subtitulo', models.CharField(default='--', max_length=300)),
                ('historia', models.CharField(default='--', max_length=10000)),
                ('ubicacion', models.CharField(default='--', max_length=80)),
                ('imagen', models.ImageField(default='Default.jpg', null=True, upload_to='fotos')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='--')),
                ('usuario', models.CharField(default='--', max_length=60)),
                ('nombre', models.ForeignKey(default='--', on_delete=django.db.models.deletion.CASCADE, to='WebCaosNews.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebCaosNews.noticia')),
            ],
        ),
    ]
