# Generated by Django 4.0.5 on 2022-07-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCaosNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='users/User_Defecto.jpg', upload_to='users'),
        ),
    ]
