# Generated by Django 4.0.5 on 2022-07-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCaosNews', '0002_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='Default.jpg', null=True, upload_to='fotos'),
        ),
    ]
