# Generated by Django 4.0.5 on 2022-07-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCaosNews', '0003_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='Default.jpg', upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='Default.jpg', upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='User_Defecto.jpg', upload_to='users'),
        ),
    ]
