# Generated by Django 4.0.5 on 2022-07-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCaosNews', '0004_alter_categoria_imagen_alter_noticia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='Falta_imagen.jpg', upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='Falta_imagen.jpg', upload_to='fotos'),
        ),
    ]
